spring:
  application:
    name: back
  profiles:
    include: secret
  ai:
    openai:
      base-url: https://api.groq.com/openai
      api-key: ON_SECRET
      chat:
        options:
          model: meta-llama/llama-4-scout-17b-16e-instruct
          temperature: 0